version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: lms_postgres
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_DB=lmstest
      - POSTGRES_USER=lmsuser
      - POSTGRES_PASSWORD=lmsroot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lms_network

networks:
  lms_network:
    driver: bridge

volumes:
  postgres_data:
