version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: lms_postgres
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_DB=lmstest
      - POSTGRES_USER=lmsuser
      - POSTGRES_PASSWORD=lmsroot
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    container_name: lms_redis

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kafka_data:/kafka

networks:
  default:
    external: true
    name: lms_network

volumes:
  postgres_data:
  kafka_data:
