spring:
  application:
    name: lms
  profiles:
    active: dev
  security:
    user:
      name: lms
      password: 82580bab-c552-4946-b017-43a6f072e265

  datasource:
    url: jdbc:postgresql://lms_postgres:5432/lmstest
    username: lmsuser
    password: lmsroot

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Kiev
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

  jackson:
    time-zone: Europe/Kiev

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
