spring:
  application:
    name: lms

  datasource:
    url: jdbc:postgresql://localhost:5444/lmstest
    username: lmsuser
    password: lmsroot

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Kiev
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

  jackson:
    time-zone: Europe/Kiev
