server:
  port: 8080

logging:
  level:
    root: info
    org.springframework: warn
    org.hibernate: warn
    org.springframework.security: warn

spring:
  application:
    name: lms

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      client-id: "demo-consumer"

    producer:
      client-id: "demo-producer"

  profiles:
    active: dev

  security:
    user:
      name: lms
      password: 82580bab-c552-4946-b017-43a6f072e265

  datasource:
    url: jdbc:postgresql://lms_postgres:5432/lmstest
    username: lmsuser
    password: lmsroot

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Kiev
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

  jackson:
    time-zone: Europe/Kiev

  data:
    redis:
      port: 6379
      database: 0
      host: lms_redis

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

jwt:
  access-token-expiration-minutes: 10
  refresh-token-expiration-hours: 1

springdoc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha

app:
  env: dev
  kafka:
    topic: "demo-topic"
